// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	payment_gateway "bayareen-backend/features/payment_gateway"

	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// CreateInvoice provides a mock function with given fields: _a0
func (_m *Data) CreateInvoice(_a0 payment_gateway.InvoiceObj) (payment_gateway.InvoiceData, error) {
	ret := _m.Called(_a0)

	var r0 payment_gateway.InvoiceData
	if rf, ok := ret.Get(0).(func(payment_gateway.InvoiceObj) payment_gateway.InvoiceData); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(payment_gateway.InvoiceData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(payment_gateway.InvoiceObj) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvoice provides a mock function with given fields: _a0
func (_m *Data) GetInvoice(_a0 string) (payment_gateway.InvoiceData, error) {
	ret := _m.Called(_a0)

	var r0 payment_gateway.InvoiceData
	if rf, ok := ret.Get(0).(func(string) payment_gateway.InvoiceData); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(payment_gateway.InvoiceData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
