// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import providers "bayareen-backend/features/providers"

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// Create provides a mock function with given fields: data
func (_m *Data) Create(data *providers.Core) (*providers.Core, error) {
	ret := _m.Called(data)

	var r0 *providers.Core
	if rf, ok := ret.Get(0).(func(*providers.Core) *providers.Core); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*providers.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Data) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Data) GetAll() []providers.Core {
	ret := _m.Called()

	var r0 []providers.Core
	if rf, ok := ret.Get(0).(func() []providers.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]providers.Core)
		}
	}

	return r0
}

// GetByCategoryId provides a mock function with given fields: catId
func (_m *Data) GetByCategoryId(catId int) ([]providers.Core, error) {
	ret := _m.Called(catId)

	var r0 []providers.Core
	if rf, ok := ret.Get(0).(func(int) []providers.Core); ok {
		r0 = rf(catId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]providers.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(catId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Data) GetById(id int) (*providers.Core, error) {
	ret := _m.Called(id)

	var r0 *providers.Core
	if rf, ok := ret.Get(0).(func(int) *providers.Core); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: data
func (_m *Data) Update(data *providers.Core) (*providers.Core, error) {
	ret := _m.Called(data)

	var r0 *providers.Core
	if rf, ok := ret.Get(0).(func(*providers.Core) *providers.Core); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*providers.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
