// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	email "bayareen-backend/features/email"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ParseTemplate provides a mock function with given fields: fileName, r, data
func (_m *Service) ParseTemplate(fileName string, r *email.Request, data interface{}) error {
	ret := _m.Called(fileName, r, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *email.Request, interface{}) error); ok {
		r0 = rf(fileName, r, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: templateName, r, items
func (_m *Service) Send(templateName string, r *email.Request, items interface{}) error {
	ret := _m.Called(templateName, r, items)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *email.Request, interface{}) error); ok {
		r0 = rf(templateName, r, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMail provides a mock function with given fields: r
func (_m *Service) SendMail(r *email.Request) error {
	ret := _m.Called(r)

	var r0 error
	if rf, ok := ret.Get(0).(func(*email.Request) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
